version: '3.8'
services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: laravel-10
        # extra_hosts:
        #     - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-9000}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        # environment:
        #     WWWUSER: '${WWWUSER}'
        #     LARAVEL_SAIL: 1
        #     XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        #     XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: 'processtooldb'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_ROOT_HOST: 'mysql'
            MYSQL_DATABASE: 'process_tool_db'
            MYSQL_USER: 'pt_db_admin'
            MYSQL_PASSWORD: '17dqPXm9j6O|_AcA'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './mysql:/var/lib/mysql'
            # - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        # healthcheck:
        #     test:
        #         - CMD
        #         - mysqladmin
        #         - ping
        #         - '-p${DB_PASSWORD}'
        #     retries: 3
        #     timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local